scene.setBackgroundColor(15)
let mySprite = sprites.create(assets.image`myImage`, SpriteKind.Food)
mySprite = sprites.create(assets.image`myImage`, SpriteKind.Food)
mySprite = sprites.create(assets.image`myImage`, SpriteKind.Food)
mySprite = sprites.create(assets.image`myImage`, SpriteKind.Food)
mySprite = sprites.create(assets.image`myImage`, SpriteKind.Food)
